FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y --no-install-recommends  python3-pip python3.8-dev libcurl4 curl libpq-dev libcurl4-openssl-dev libssl-dev  swig3.0 unixodbc-dev build-essential libssl-dev libffi-dev wget tzdata\
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python && ln -s /usr/bin/swig3.0 /usr/bin/swig \
  && pip3 install --upgrade pip 

#Clear stale code everytime
RUN rm -rf /home/app 

RUN mkdir /home/app
WORKDIR /home/app
COPY . /home/app/

ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV VIRTUAL_ENV=/home/flexydialenv

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip3 --no-cache install virtualenv && virtualenv ../flexydialenv \
    && /home/flexydialenv/bin/python -m pip install --upgrade pip

RUN pip3 install -r ./requirements.txt

RUN mkdir -p /var/lib/flexydial/media/upload
RUN chmod -R 755 /var/lib/flexydial