# Generated by Django 2.2 on 2019-09-10 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diallereventlog',
            name='bill_sec',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), editable=False, null=True, verbose_name='Talk Time'),
        ),
    ]
