# Generated by Django 2.2 on 2019-09-16 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_auto_20190911_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='ibc_popup',
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='blended_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='blended_wait_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='calldetail',
            name='blended_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='calldetail',
            name='blended_wait_time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
