# Generated by Django 2.2 on 2019-09-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_auto_20190916_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrfeedbck',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
