# Generated by Django 2.2 on 2019-09-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0005_auto_20190916_1825'),
        ('callcenter', '0005_cdrfeedbck_comment'),
    ]

    operations = [
    ]
