# Generated by Django 2.2 on 2019-09-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0006_merge_20190918_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentactivity',
            name='mute_time',
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.35', help_text='Server IP address', max_length=100),
        ),
    ]
