# Generated by Django 2.2 on 2019-09-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0008_calldetail_hangup_source'),
        ('callcenter', '0007_auto_20190919_1601'),
    ]

    operations = [
    ]
