# Generated by Django 2.2 on 2019-09-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0009_merge_20190920_1848'),
        ('callcenter', '0005_auto_20190916_1712'),
    ]

    operations = [
    ]
