# Generated by Django 2.2 on 2019-10-05 11:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0012_auto_20190925_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.0.104', help_text='Server IP address', max_length=100),
        ),
        migrations.CreateModel(
            name='SkilledRouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('skill_id', models.BigIntegerField(null=True, unique=True)),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callcenter.CampaignSchedule')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': '-created',
            },
        ),
    ]
