# Generated by Django 2.2 on 2019-10-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('callcenter', '0013_auto_20191009_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abundantcall',
            new_name='Abandonedcall',
        ),
    ]
