# Generated by Django 2.2 on 2019-10-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0014_auto_20191010_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abandonedcall',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandoned', 'Abandoned'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='callbackcontact',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandoned', 'Abandoned'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='dialed_status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Drop', 'Drop'), ('Abandoned', 'Abandoned'), ('Auto-Dialed', 'Auto-Dialed'), ('Dialed', 'Dialed'), ('Agent-Answered', 'Agent-Answered'), ('INVALID_NUMBER', 'INVALID_NUMBER')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='currentcallback',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandoned', 'Abandoned'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='diallereventlog',
            name='dialed_status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Drop', 'Drop'), ('Abandoned', 'Abandoned'), ('Auto-Dialed', 'Auto-Dialed'), ('Dialed', 'Dialed'), ('Agent-Answered', 'Agent-Answered'), ('INVALID_NUMBER', 'INVALID_NUMBER')], default='', max_length=50),
        ),
    ]
