# Generated by Django 2.2 on 2019-10-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0013_auto_20191005_1145'),
        ('callcenter', '0015_auto_20191010_1230'),
    ]

    operations = [
    ]
