# Generated by Django 2.2 on 2019-10-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0015_auto_20191010_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.52', help_text='Server IP address', max_length=100),
        ),
    ]
