# Generated by Django 2.2 on 2019-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0016_merge_20191016_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilledrouting',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.37', help_text='Server IP address', max_length=100),
        ),
    ]
