# Generated by Django 2.2 on 2019-10-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0016_auto_20191030_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='css',
            name='campaign',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
