# Generated by Django 2.2 on 2019-10-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0016_datauploadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datauploadlog',
            name='phonebook',
        ),
    ]
