# Generated by Django 2.2 on 2019-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0017_remove_datauploadlog_phonebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauploadlog',
            name='status',
            field=models.CharField(choices=[(0, 'InProgress'), (1, 'Completed')], default=0, max_length=15),
        ),
    ]
