# Generated by Django 2.2 on 2019-10-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0017_css_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='css_query',
        ),
    ]
