# Generated by Django 2.2 on 2019-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0017_auto_20191017_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='namespace_fields',
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.36', help_text='Server IP address', max_length=100),
        ),
    ]
