# Generated by Django 2.2 on 2019-10-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0018_remove_campaign_css_query'),
        ('callcenter', '0018_auto_20191023_1542'),
    ]

    operations = [
    ]
