# Generated by Django 2.2 on 2019-11-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0019_merge_20191031_1917'),
        ('callcenter', '0018_datauploadlog_status'),
        ('callcenter', '0019_merge_20191031_1921'),
    ]

    operations = [
    ]
