# Generated by Django 2.2 on 2019-11-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0020_merge_20191101_1244'),
        ('callcenter', '0021_auto_20191101_1559'),
    ]

    operations = [
    ]
