# Generated by Django 2.2 on 2019-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0023_auto_20191107_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='callback_threshold',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
