# Generated by Django 2.2 on 2019-11-09 16:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0024_auto_20191107_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilledrouting',
            name='audio',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilledrouting',
            name='hash_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skilledrouting',
            name='star_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.72', help_text='Server IP address', max_length=100),
        ),
    ]
