# Generated by Django 2.2 on 2019-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0024_auto_20191107_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcallback',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
