# Generated by Django 2.2 on 2019-11-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0025_auto_20191109_1636'),
        ('callcenter', '0025_auto_20191108_1333'),
    ]

    operations = [
    ]
