# Generated by Django 2.2 on 2019-11-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0026_merge_20191111_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilledrouting',
            name='hash_key',
        ),
        migrations.RemoveField(
            model_name='skilledrouting',
            name='star_key',
        ),
    ]
