# Generated by Django 2.2 on 2019-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0026_auto_20191109_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcallback',
            name='callbackcontact_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
