# Generated by Django 2.2 on 2019-11-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0028_currentcallback_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackcontact',
            name='assigned_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='callbackcontact',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
