# Generated by Django 2.2 on 2019-11-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0029_auto_20191111_1703'),
        ('callcenter', '0025_auto_20191109_1636'),
    ]

    operations = [
    ]
