# Generated by Django 2.2 on 2019-11-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0027_auto_20191111_1524'),
        ('callcenter', '0030_merge_20191112_1156'),
    ]

    operations = [
    ]
