# Generated by Django 2.2 on 2019-11-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0032_auto_20191113_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtag',
            name='relation_type',
            field=models.CharField(choices=[('multifield', 'MultiField'), ('dropdown', 'DropDown')], default='dropdown', max_length=10),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.36', help_text='Server IP address', max_length=100),
        ),
    ]
