# Generated by Django 2.2 on 2019-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0034_auto_20191125_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilledrouting',
            name='d_abandoned_camp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skilledrouting',
            name='skill_papup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abandonedcall',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandonedcall', 'Abandonedcall'), ('Drop', 'Drop'), ('Dnc', 'Dnc'), ('NC', 'NC'), ('Invalid Number', 'Invalid Number')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='callbackcontact',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandonedcall', 'Abandonedcall'), ('Drop', 'Drop'), ('Dnc', 'Dnc'), ('NC', 'NC'), ('Invalid Number', 'Invalid Number')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='currentcallback',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandonedcall', 'Abandonedcall'), ('Drop', 'Drop'), ('Dnc', 'Dnc'), ('NC', 'NC'), ('Invalid Number', 'Invalid Number')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.37', help_text='Server IP address', max_length=100),
        ),
    ]
