# Generated by Django 2.2 on 2019-12-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0035_auto_20191216_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilledrouting',
            old_name='skill_papup',
            new_name='skill_popup',
        ),
    ]
