# Generated by Django 2.2 on 2019-12-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0036_auto_20191216_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilledrouting',
            name='callback',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
