# Generated by Django 2.2 on 2019-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0037_skilledrouting_callback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilledrouting',
            name='callback',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
