# Generated by Django 2.2 on 2019-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0039_auto_20191219_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackcontact',
            name='callmode',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
    ]
