# Generated by Django 2.2 on 2019-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0040_callbackcontact_callmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcallback',
            name='callmode',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
    ]
