# Generated by Django 2.2 on 2019-12-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0041_currentcallback_callmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_ac_dial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='auto_qcb_dial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
