# Generated by Django 2.2 on 2020-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0042_auto_20191230_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackcontact',
            name='phonebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentcallback',
            name='phonebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.49', help_text='Server IP address', max_length=100),
        ),
    ]
