# Generated by Django 2.2 on 2020-01-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0042_auto_20191231_1607'),
        ('callcenter', '0042_auto_20191230_1903'),
    ]

    operations = [
    ]
