# Generated by Django 2.2 on 2020-01-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0043_merge_20200102_1122'),
        ('callcenter', '0043_auto_20200108_1711'),
    ]

    operations = [
    ]
