# Generated by Django 2.2 on 2020-01-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0045_auto_20200113_1212'),
        ('callcenter', '0045_auto_20200113_1838'),
    ]

    operations = [
    ]
