# Generated by Django 2.2 on 2020-01-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0046_merge_20200120_1005'),
        ('callcenter', '0045_auto_20200113_1921'),
    ]

    operations = [
    ]
