# Generated by Django 2.2 on 2020-01-20 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0047_merge_20200120_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='ivr_duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name='diallereventlog',
            name='ivr_duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.37', help_text='Server IP address', max_length=100),
        ),
    ]
