# Generated by Django 2.2 on 2020-01-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0047_merge_20200120_1116'),
        ('callcenter', '0047_merge_20200120_1136'),
    ]

    operations = [
    ]
