# Generated by Django 2.2 on 2020-01-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0049_merge_20200121_1149'),
        ('callcenter', '0048_merge_20200121_1218'),
    ]

    operations = [
    ]
