# Generated by Django 2.2 on 2020-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0051_auto_20200123_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrfeedbck',
            name='primary_dispo',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.35', help_text='Server IP address', max_length=100),
        ),
    ]
