# Generated by Django 2.2 on 2020-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0052_auto_20200130_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.37', help_text='Server IP address', max_length=100),
        ),
    ]
