# Generated by Django 2.2 on 2020-02-18 17:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0053_auto_20200217_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lead_priotize',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.149', help_text='Server IP address', max_length=100),
        ),
    ]
