# Generated by Django 2.2 on 2020-02-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0054_auto_20200218_1715'),
        ('callcenter', '0053_campaignvariable_hold_music'),
    ]

    operations = [
    ]
