# Generated by Django 2.2 on 2020-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0055_merge_20200219_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='alternate_num_dial',
            new_name='search_alternate',
        ),
    ]
