# Generated by Django 2.2 on 2020-03-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0056_auto_20200228_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrfeedbck',
            name='calldetail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdrfeedback', to='callcenter.CallDetail'),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.36', help_text='Server IP address', max_length=100),
        ),
    ]
