# Generated by Django 2.2 on 2020-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0058_auto_20200313_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='10.12.2.5', help_text='Server IP address', max_length=100),
        ),
    ]
