# Generated by Django 2.2 on 2020-03-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0058_auto_20200313_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='wfh',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='uservariable',
            name='wfh_numeric',
            field=models.BigIntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
