# Generated by Django 2.2 on 2020-04-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0062_campaign_wfh_request_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservariable',
            name='w_req_callback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='call_type',
            field=models.CharField(choices=[('webrtc', 'Webrtc'), ('softcall', 'SoftCall'), ('2', 'Mobile')], default='webrtc', max_length=100),
        ),
    ]
