# Generated by Django 2.2 on 2020-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0063_auto_20200402_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='w_req_callback',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
