# Generated by Django 2.2 on 2020-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0065_thirdpartyapiusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyapiusertoken',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
