# Generated by Django 2.2 on 2020-04-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0066_thirdpartyapiusertoken_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyapiusertoken',
            name='last_ip_addresss',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
