# Generated by Django 2.2 on 2020-04-15 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0067_thirdpartyapiusertoken_last_ip_addresss'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyapiusertoken',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
