# Generated by Django 2.2 on 2020-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0068_thirdpartyapiusertoken_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyapiusertoken',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
