# Generated by Django 2.2 on 2020-04-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0071_auto_20200420_1856'),
        ('callcenter', '0059_auto_20200415_0953'),
    ]

    operations = [
    ]
