# Generated by Django 2.2 on 2020-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0072_merge_20200422_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dap_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='10.12.2.7', help_text='Server IP address', max_length=100),
        ),
    ]
