# Generated by Django 2.2 on 2020-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0074_auto_20200523_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgateway',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
