# Generated by Django 2.2 on 2020-05-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0075_smsgateway_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsgateway',
            name='key',
            field=models.CharField(max_length=1032, null=True),
        ),
    ]
