# Generated by Django 2.2 on 2020-05-27 15:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0076_auto_20200523_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.77', help_text='Server IP address', max_length=100),
        ),
        migrations.CreateModel(
            name='ThirdPartyApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('dynamic_api', models.BooleanField(default=False)),
                ('click_url', models.BooleanField(default=False)),
                ('weburl', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.ManyToManyField(blank=True, null=True, related_name='apicampaign', to='callcenter.Campaign')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': '-created',
            },
        ),
    ]
