# Generated by Django 2.2 on 2020-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0076_auto_20200523_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(help_text='employee_id', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.138', help_text='Server IP address', max_length=100),
        ),
    ]
