# Generated by Django 2.2 on 2020-05-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0077_auto_20200527_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='dap_status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='thirdparty_api_status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='weburl',
        ),
    ]
