# Generated by Django 2.2 on 2020-05-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0077_auto_20200527_0942'),
        ('callcenter', '0078_auto_20200527_1532'),
    ]

    operations = [
    ]
