# Generated by Django 2.2 on 2020-05-29 11:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0079_merge_20200528_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='vb_audio',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='vb_data',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='vb_mode',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='voice_blaster',
        ),
        migrations.AlterField(
            model_name='smsgateway',
            name='sms_trigger_on',
            field=models.CharField(choices=[('0', 'On Pre-Call'), ('1', 'On Disposition'), ('2', 'On Call')], default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.77', help_text='Server IP address', max_length=100),
        ),
        migrations.CreateModel(
            name='VoiceBlaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('voice_blaster', models.BooleanField(default=False)),
                ('vb_mode', models.CharField(choices=[('0', 'Audio File'), ('1', 'TTS(Text to speech)')], db_index=True, max_length=2, null=True)),
                ('vb_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.ManyToManyField(blank=True, null=True, related_name='vbcampaign', to='callcenter.Campaign')),
                ('vb_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_blaster_audio', to='callcenter.AudioFile')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': '-created',
            },
        ),
    ]
