# Generated by Django 2.2 on 2020-05-28 15:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0080_auto_20200528_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dap_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='thirdparty_api_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='weburl',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
