# Generated by Django 2.2 on 2020-06-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0080_auto_20200529_1928'),
        ('callcenter', '0080_auto_20200529_1142'),
    ]

    operations = [
    ]
