# Generated by Django 2.2 on 2020-06-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0081_merge_20200603_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonebookBucketCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_login_count', models.IntegerField(default=0)),
                ('is_contact', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pb_campaign', to='callcenter.Campaign')),
            ],
        ),
    ]
