# Generated by Django 2.2 on 2020-05-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0081_auto_20200528_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='dap_status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='thirdparty_api_status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='weburl',
        ),
    ]
