# Generated by Django 2.2 on 2020-06-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('callcenter', '0081_merge_20200603_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='trunk',
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.0.102', help_text='Server IP address', max_length=100),
        ),
        migrations.CreateModel(
            name='DialTrunkPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, db_index=True, default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('dial_trunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dial_trunk', to='callcenter.DialTrunk')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='trunk',
            field=models.ManyToManyField(blank=True, null=True, related_name='trunk', to='callcenter.DialTrunkPriority'),
        ),
    ]
