# Generated by Django 2.2 on 2020-06-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0080_auto_20200529_1928'),
        ('callcenter', '0082_auto_20200528_1543'),
    ]

    operations = [
    ]
