# Generated by Django 2.2 on 2020-06-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('callcenter', '0082_auto_20200608_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaTrunkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_channel_count', models.IntegerField(blank=True, db_index=True, default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
                ('trunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_trunk', to='callcenter.DialTrunk')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_trunk_group',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='trunk',
        ),
        migrations.AddField(
            model_name='campaign',
            name='trunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trunk', to='callcenter.DialTrunk'),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.0.101', help_text='Server IP address', max_length=100),
        ),
        migrations.DeleteModel(
            name='DialTrunkPriority',
        ),
        migrations.AddField(
            model_name='campaign',
            name='trunk_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trunk_group', to='callcenter.DiaTrunkGroup'),
        ),
    ]
