# Generated by Django 2.2 on 2020-06-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('callcenter', '0083_auto_20200611_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diatrunkgroup',
            old_name='modified_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='diatrunkgroup',
            name='trunk',
        ),
        migrations.CreateModel(
            name='DialTrunkPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, db_index=True, default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
                ('trunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_trunk', to='callcenter.DialTrunk')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='diatrunkgroup',
            name='trunks',
            field=models.ManyToManyField(blank=True, to='callcenter.DialTrunkPriority'),
        ),
    ]
