# Generated by Django 2.2 on 2020-07-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0084_auto_20200626_1844'),
        ('callcenter', '0083_merge_20200601_1517'),
    ]

    operations = [
    ]
