# Generated by Django 2.2 on 2020-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0084_auto_20200626_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='10.12.2.12', help_text='Server IP address', max_length=100),
        ),
    ]
