# Generated by Django 2.2 on 2020-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0084_auto_20200716_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetail',
            name='uniqueid',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
