# Generated by Django 2.2 on 2020-06-11 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0084_auto_20200611_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='diatrunkgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trunk_group_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
