# Generated by Django 2.2 on 2020-06-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0082_phonebookbucketcampaign'),
        ('callcenter', '0085_diatrunkgroup_created_by'),
    ]

    operations = [
    ]
