# Generated by Django 2.2 on 2020-07-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0085_auto_20200709_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='session_uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='smslog',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_sms', to='callcenter.SMSTemplate'),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='10.12.2.10', help_text='Server IP address', max_length=100),
        ),
    ]
