# Generated by Django 2.2 on 2020-07-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0085_calldetail_uniqueid'),
        ('callcenter', '0086_auto_20200715_1342'),
    ]

    operations = [
    ]
