# Generated by Django 2.2 on 2020-07-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0086_auto_20200715_1342'),
        ('callcenter', '0085_merge_20200703_1756'),
    ]

    operations = [
    ]
