# Generated by Django 2.2 on 2020-07-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0087_merge_20200720_1430'),
        ('callcenter', '0088_auto_20200717_1421'),
    ]

    operations = [
    ]
