# Generated by Django 2.2 on 2020-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0089_auto_20200720_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='diallereventlog',
            name='campaign_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
