# Generated by Django 2.2 on 2020-07-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0090_diallereventlog_campaign_name'),
        ('callcenter', '0086_merge_20200622_1417'),
    ]

    operations = [
    ]
