# Generated by Django 2.2 on 2020-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0091_auto_20200727_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickyagent',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
