# Generated by Django 2.2 on 2020-07-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0092_stickyagent_campaign_name'),
        ('callcenter', '0089_merge_20200720_1634'),
    ]

    operations = [
    ]
