# Generated by Django 2.2 on 2020-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0092_dialtrunk_did_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialtrunkpriority',
            name='did',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dialtrunkpriority',
            name='type_of_did',
            field=models.CharField(choices=[('1', 'single did'), ('2', 'multiple did'), ('3', 'did range')], default='1', max_length=2),
        ),
    ]
