# Generated by Django 2.2 on 2020-07-27 19:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0094_auto_20200727_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='trunk_did',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
