# Generated by Django 2.2 on 2020-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0095_campaign_trunk_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_trunk_group',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.64', help_text='Server IP address', max_length=100),
        ),
    ]
