# Generated by Django 2.2 on 2020-07-29 11:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0096_auto_20200728_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='all_caller_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
