# Generated by Django 2.2 on 2020-07-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0092_stickyagent_campaign_name'),
        ('callcenter', '0097_campaign_all_caller_id'),
    ]

    operations = [
    ]
