# Generated by Django 2.2 on 2020-07-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0098_merge_20200729_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialtrunkpriority',
            name='trunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_trunk', to='callcenter.DialTrunk'),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.64', help_text='Server IP address', max_length=100),
        ),
    ]
