# Generated by Django 2.2 on 2020-07-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0093_merge_20200728_1737'),
        ('callcenter', '0098_merge_20200729_1800'),
    ]

    operations = [
    ]
