# Generated by Django 2.2 on 2020-07-30 15:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('callcenter', '0098_merge_20200729_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, db_index=True, default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_campaign', to='callcenter.Campaign')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.0.101', help_text='Server IP address', max_length=100),
        ),
        migrations.CreateModel(
            name='InGroupCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('caller_id', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('strategy', models.CharField(choices=[('0', 'Top-to-bottom'), ('1', 'Bottom-to-top'), ('2', 'Random'), ('3', 'Highest-waiting-agent')], default='0', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingroup_created_by', to=settings.AUTH_USER_MODEL)),
                ('ingroup_campaign', models.ManyToManyField(blank=True, null=True, related_name='ingroup_campaign', to='callcenter.CampaignPriority')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
    ]
