# Generated by Django 2.2 on 2020-07-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0099_auto_20200730_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpriority',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_campaign', to='callcenter.Campaign'),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.0.100', help_text='Server IP address', max_length=100),
        ),
    ]
