# Generated by Django 2.2 on 2020-07-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0099_auto_20200730_1504'),
        ('callcenter', '0099_merge_20200729_1827'),
    ]

    operations = [
    ]
