# Generated by Django 2.2 on 2020-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0099_auto_20200730_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='updatelead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.0.104', help_text='Server IP address', max_length=100),
        ),
    ]
