# Generated by Django 2.2 on 2020-08-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0100_auto_20200806_1737'),
        ('callcenter', '0100_merge_20200730_1733'),
    ]

    operations = [
    ]
