# Generated by Django 2.2 on 2020-08-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0101_merge_20200811_1614'),
        ('callcenter', '0101_auto_20200824_1718'),
    ]

    operations = [
    ]
