# Generated by Django 2.2 on 2020-08-03 13:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0101_auto_20200803_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilledrouting',
            name='skill_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
