# Generated by Django 2.2 on 2020-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0102_auto_20200902_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.0.101', help_text='Server IP address', max_length=100),
        ),
    ]
