# Generated by Django 2.2 on 2020-08-03 16:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0102_auto_20200803_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilledrouting',
            name='skill_id_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
