# Generated by Django 2.2 on 2020-09-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0103_auto_20200903_1543'),
        ('callcenter', '0102_merge_20200825_1415'),
    ]

    operations = [
    ]
