# Generated by Django 2.2 on 2020-08-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0099_auto_20200730_1504'),
        ('callcenter', '0103_skilledrouting_skill_id_list'),
    ]

    operations = [
    ]
