# Generated by Django 2.2 on 2020-09-15 12:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0103_auto_20200903_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportColumnVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(choices=[('1', 'call_detail'), ('2', 'call_recording'), ('3', 'agent_performance'), ('4', 'agent_mis'), ('5', 'agent_activity'), ('6', 'campaign_mis'), ('7', 'campaign_performance'), ('8', 'callback_call'), ('9', 'abandoned_call'), ('10', 'contact_info'), ('11', 'billing'), ('12', 'admin_log')], default='1', max_length=2)),
                ('columns_name', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
