# Generated by Django 2.2 on 2020-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0104_merge_20200909_1948'),
        ('callcenter', '0104_reportcolumnvisibility'),
    ]

    operations = [
    ]
