# Generated by Django 2.2 on 2020-09-23 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0105_auto_20200917_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecordingFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('calldetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callrecording_calldetail', to='callcenter.CallDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_call_recording', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
