# Generated by Django 2.2 on 2020-08-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0105_campaignvariable_wfh_caller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservariable',
            name='domain',
            field=models.CharField(default='192.168.3.109', help_text='Server IP address', max_length=100),
        ),
    ]
