# Generated by Django 2.2 on 2020-08-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0106_auto_20200825_2121'),
        ('callcenter', '0101_auto_20200824_1718'),
    ]

    operations = [
    ]
