# Generated by Django 2.2 on 2020-09-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0105_merge_20200918_1806'),
        ('callcenter', '0106_auto_20200922_1133'),
    ]

    operations = [
    ]
