# Generated by Django 2.2 on 2020-09-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0106_auto_20200922_1133'),
        ('callcenter', '0106_callrecordingfeedback'),
    ]

    operations = [
    ]
