# Generated by Django 2.2 on 2020-09-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0107_merge_20200922_1507'),
        ('callcenter', '0107_merge_20200924_2018'),
    ]

    operations = [
    ]
