# Generated by Django 2.2 on 2020-10-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0107_merge_20200828_2043'),
        ('callcenter', '0107_merge_20200924_2018'),
    ]

    operations = [
    ]
