# Generated by Django 2.2 on 2020-10-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0108_merge_20201001_1630'),
        ('callcenter', '0108_merge_20200925_1324'),
    ]

    operations = [
    ]
