# Generated by Django 2.2 on 2020-11-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0108_auto_20201012_1456'),
        ('callcenter', '0108_merge_20201001_1630'),
    ]

    operations = [
    ]
