# Generated by Django 2.2 on 2020-11-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0110_auto_20201109_2111'),
        ('callcenter', '0109_merge_20201109_1807'),
    ]

    operations = [
    ]
