# Generated by Django 2.2 on 2020-11-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0111_merge_20201111_1144'),
        ('callcenter', '0111_merge_20201110_1820'),
    ]

    operations = [
    ]
