# Generated by Django 2.2 on 2020-11-16 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('callcenter', '0112_merge_20201111_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportcolumnvisibility',
            name='report_name',
            field=models.CharField(choices=[('1', 'call_detail'), ('2', 'call_recording'), ('3', 'agent_performance'), ('4', 'agent_mis'), ('5', 'agent_activity'), ('6', 'campaign_mis'), ('7', 'campaign_performance'), ('8', 'callback_call'), ('9', 'abandoned_call'), ('10', 'contact_info'), ('11', 'billing'), ('12', 'admin_log'), ('13', 'call_recording_feedback'), ('14', 'alternate_number'), ('15', 'management_performace')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email_subject', models.CharField(default='', max_length=255)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('campaign', models.ManyToManyField(blank=True, null=True, related_name='email_campaign', to='callcenter.Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_created_by', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='EmailGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email_host', models.CharField(max_length=1032)),
                ('email_port', models.IntegerField()),
                ('default_email', models.CharField(blank=True, max_length=1032, null=True)),
                ('default_email_password', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('email_trigger_on', models.CharField(choices=[('0', 'On Pre-Call'), ('1', 'On Disposition'), ('2', 'On Call')], default='2', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailgateway_created_by', to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ManyToManyField(blank=True, to='callcenter.Disposition')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
                ('template', models.ManyToManyField(blank=True, to='callcenter.EmailTemplate')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callcenter.EmailGateway'),
        ),
    ]
