# Generated by Django 2.2 on 2020-11-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0113_auto_20201116_2037'),
        ('callcenter', '0109_merge_20201019_1808'),
    ]

    operations = [
    ]
