# Generated by Django 2.2 on 2021-01-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0114_auto_20210111_1621'),
        ('callcenter', '0114_auto_20201230_1645'),
    ]

    operations = [
    ]
