# Generated by Django 2.2 on 2021-01-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0115_auto_20201217_1437'),
        ('callcenter', '0114_auto_20201230_1645'),
    ]

    operations = [
    ]
