# Generated by Django 2.2 on 2021-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0116_auto_20210202_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='rpc_port',
            field=models.IntegerField(default=8080, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='sip_udp_port',
            field=models.IntegerField(default=45060, null=True),
        ),
        migrations.AddField(
            model_name='switch',
            name='wss_port',
            field=models.IntegerField(default=7444, null=True),
        ),
        migrations.AlterField(
            model_name='reportcolumnvisibility',
            name='report_name',
            field=models.CharField(choices=[('1', 'call_detail'), ('2', 'call_recording'), ('3', 'agent_performance'), ('4', 'agent_mis'), ('5', 'agent_activity'), ('6', 'campaign_mis'), ('7', 'campaign_performance'), ('8', 'callback_call'), ('9', 'abandoned_call'), ('10', 'contact_info'), ('11', 'billing'), ('12', 'admin_log'), ('13', 'call_recording_feedback'), ('14', 'alternate_number'), ('15', 'management_performace'), ('16', 'lan')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='call_type',
            field=models.CharField(choices=[('webrtc', 'Webrtc'), ('softcall', 'SoftCall'), ('2', 'Mobile'), ('3', 'IpPhone')], default='webrtc', max_length=100),
        ),
    ]
