# Generated by Django 2.2 on 2021-01-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0116_merge_20210105_1919'),
        ('callcenter', '0115_merge_20210112_0522'),
    ]

    operations = [
    ]
