# Generated by Django 2.2 on 2021-02-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0116_auto_20210202_1608'),
        ('callcenter', '0117_merge_20210118_1231'),
    ]

    operations = [
    ]
