# Generated by Django 2.2 on 2021-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0117_auto_20210222_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pausebreak',
            name='inactive_on_exceed',
            field=models.BooleanField(default=True),
        ),
    ]
