# Generated by Django 2.2 on 2021-03-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0117_auto_20210222_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilledrouting',
            name='skill_id_list',
        ),
        migrations.CreateModel(
            name='SkilledRoutingCallerid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_id', models.CharField(blank=True, max_length=100, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillroute_callerid', to='callcenter.SkilledRouting')),
            ],
        ),
    ]
