# Generated by Django 2.2 on 2021-02-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0117_auto_20210222_1108'),
        ('callcenter', '0118_merge_20210203_1355'),
    ]

    operations = [
    ]
