# Generated by Django 2.2 on 2021-03-02 14:49

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0118_pausebreak_inactive_on_exceed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('0', 'info'), ('1', 'warning'), ('2', 'danger')], default='0', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
