# Generated by Django 2.2 on 2021-03-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0119_merge_20210224_1347'),
        ('callcenter', '0118_auto_20210306_1631'),
    ]

    operations = [
    ]
