# Generated by Django 2.2 on 2021-03-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0118_auto_20210306_1631'),
        ('callcenter', '0119_broadcastmessages'),
    ]

    operations = [
    ]
