# Generated by Django 2.2 on 2021-03-17 14:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0120_merge_20210315_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessages',
            name='broadcast_time',
            field=models.CharField(default='5', max_length=4),
        ),
        migrations.AlterField(
            model_name='broadcastmessages',
            name='receivers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
