# Generated by Django 2.2 on 2021-03-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0120_merge_20210315_1110'),
        ('callcenter', '0120_merge_20210306_1638'),
    ]

    operations = [
    ]
