# Generated by Django 2.2 on 2021-04-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0121_auto_20210317_1443'),
        ('callcenter', '0121_daemons'),
    ]

    operations = [
    ]
