# Generated by Django 2.2 on 2021-03-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0121_auto_20210317_1443'),
        ('callcenter', '0121_merge_20210315_1146'),
    ]

    operations = [
    ]
