# Generated by Django 2.2 on 2021-04-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0122_merge_20210401_1227'),
        ('callcenter', '0122_merge_20210318_1147'),
    ]

    operations = [
    ]
