# Generated by Django 2.2 on 2021-04-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0123_auto_20210430_1142'),
        ('callcenter', '0123_merge_20210409_1843'),
    ]

    operations = [
    ]
