# Generated by Django 2.2 on 2021-08-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0124_merge_20210430_1208'),
        ('callcenter', '0124_auto_20210713_1542'),
    ]

    operations = [
    ]
