# Generated by Django 2.2 on 2021-08-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0124_auto_20210713_1542'),
        ('callcenter', '0124_auto_20210726_1153'),
    ]

    operations = [
    ]
