# Generated by Django 2.2 on 2021-08-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0125_merge_20210805_1501'),
        ('callcenter', '0125_merge_20210802_1128'),
    ]

    operations = [
    ]
