# Generated by Django 2.2 on 2022-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0126_merge_20210805_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
