# Generated by Django 2.2 on 2022-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0127_auto_20220430_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
