# Generated by Django 2.2 on 2022-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0128_sourcelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='campaign_name',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='customer_cid',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
    ]
