# Generated by Django 2.2 on 2022-05-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0129_auto_20220509_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdpartyapidisposition',
            old_name='subdisposition',
            new_name='disposition_desc',
        ),
        migrations.RemoveField(
            model_name='thirdpartyapidisposition',
            name='callback',
        ),
        migrations.AddField(
            model_name='thirdpartyapidisposition',
            name='callBackDate',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='thirdpartyapidisposition',
            name='callBackTime',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='thirdpartyapidisposition',
            name='flexyAgentId',
            field=models.CharField(default='', max_length=10),
        ),
    ]
