# Generated by Django 2.2 on 2022-07-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0131_thirdpartyapidisposition_callid'),
        ('callcenter', '0129_auto_20220624_1706'),
    ]

    operations = [
    ]
