# Generated by Django 2.2 on 2022-07-21 05:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0132_merge_20220714_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgateway',
            name='gateway_mode',
            field=models.CharField(choices=[('0', 'Sms'), ('1', 'Whats-App')], default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsgateway',
            name='url_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
