# Generated by Django 2.2 on 2022-07-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0132_merge_20220714_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
