# Generated by Django 2.2 on 2022-07-15 20:42

import callcenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0133_audiofile_audio_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='diallereventlog',
            name='callserver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Call Server IP'),
        ),
        migrations.AddField(
            model_name='diallereventlog',
            name='recording_file',
            field=models.FileField(blank=True, upload_to=callcenter.models.get_upload_path),
        ),
    ]
