# Generated by Django 2.2 on 2022-07-25 21:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0134_campaign_whatsapp_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgateway',
            name='trigger_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
