# Generated by Django 2.2 on 2022-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0134_auto_20220715_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactivity',
            name='break_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentactivity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='agentactivity',
            name='event_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='dialed_status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Drop', 'Drop'), ('Abandoned', 'Abandoned'), ('Auto-Dialed', 'Auto-Dialed'), ('Dialed', 'Dialed'), ('Agent-Answered', 'Agent-Answered'), ('INVALID_NUMBER', 'INVALID_NUMBER')], db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='uniqueid',
            field=models.CharField(db_index=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cdrfeedbck',
            name='primary_dispo',
            field=models.CharField(db_index=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='diallereventlog',
            name='init_time',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='campaign',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='uservariable',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
