# Generated by Django 2.2 on 2022-08-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0135_smsgateway_trigger_params'),
        ('callcenter', '0135_auto_20220720_1403'),
    ]

    operations = [
    ]
