# Generated by Django 2.2 on 2022-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0137_auto_20220822_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='session_uuid',
            field=models.UUIDField(db_index=True, null=True, unique=True),
        ),
    ]
