# Generated by Django 2.2 on 2022-12-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0138_auto_20220810_1633'),
        ('callcenter', '0138_dialtrunk_did_regex'),
    ]

    operations = [
    ]
