# Generated by Django 2.2 on 2022-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0138_dialtrunk_did_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='diallereventlog',
            name='occurence_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abandonedcall',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandonedcall', 'Abandonedcall'), ('Drop', 'Drop'), ('Dnc', 'Dnc'), ('NC', 'NC'), ('Invalid Number', 'Invalid Number'), ('CBR', 'CBR'), ('Queued-Abandonedcall', 'Queued-Abandonedcall'), ('Queued-Callback', 'Queued-Callback'), ('Dialed-Queued', 'Dialed-Queued'), ('AutoFeedback', 'AutoFeedback'), ('AutoWrapUp', 'AutoWrapUp')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='callbackcontact',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandonedcall', 'Abandonedcall'), ('Drop', 'Drop'), ('Dnc', 'Dnc'), ('NC', 'NC'), ('Invalid Number', 'Invalid Number'), ('CBR', 'CBR'), ('Queued-Abandonedcall', 'Queued-Abandonedcall'), ('Queued-Callback', 'Queued-Callback'), ('Dialed-Queued', 'Dialed-Queued'), ('AutoFeedback', 'AutoFeedback'), ('AutoWrapUp', 'AutoWrapUp')], db_index=True, default='NotDialed', max_length=15),
        ),
        migrations.AlterField(
            model_name='currentcallback',
            name='status',
            field=models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('Snoozed', 'Snoozed'), ('Abandonedcall', 'Abandonedcall'), ('Drop', 'Drop'), ('Dnc', 'Dnc'), ('NC', 'NC'), ('Invalid Number', 'Invalid Number'), ('CBR', 'CBR'), ('Queued-Abandonedcall', 'Queued-Abandonedcall'), ('Queued-Callback', 'Queued-Callback'), ('Dialed-Queued', 'Dialed-Queued'), ('AutoFeedback', 'AutoFeedback'), ('AutoWrapUp', 'AutoWrapUp')], db_index=True, default='NotDialed', max_length=15),
        ),
    ]
