# Generated by Django 2.2 on 2022-12-14 12:31

import callcenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0138_dialtrunk_did_regex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(blank=True, max_length=30, null=True)),
                ('credentials_path', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_type', models.CharField(blank=True, default='GCP', max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='diallereventlog',
            name='recording_file',
            field=models.FileField(blank=True, storage=callcenter.models.AWSCustomBucketSelection(), upload_to=callcenter.models.get_upload_path),
        ),
    ]
