# Generated by Django 2.2 on 2022-12-14 12:42

import callcenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0139_auto_20221214_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketcredentials',
            name='credentials_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
