# Generated by Django 2.2 on 2022-12-14 12:46

import callcenter.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0140_auto_20221214_1242'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='bucketcredentials',
            name='credentials_path',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        
    ]
