# Generated by Django 2.2 on 2022-12-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0141_auto_20221214_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketcredentials',
            old_name='bucket_name',
            new_name='storage_bucket_name',
        ),
        migrations.RenameField(
            model_name='bucketcredentials',
            old_name='credentials_path',
            new_name='storage_credentials',
        ),
        migrations.AlterField(
            model_name='bucketcredentials',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('GCP', 'GCP'), ('AWS', 'AWS')], max_length=30, null=True),
        ),
    ]
