# Generated by Django 2.2 on 2022-12-14 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0143_auto_20221214_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketcredentials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bucketcredentials_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bucketcredentials',
            name='storage_credentials',
            field=models.CharField(help_text='\nIf storage type is GCP Simply copy the content in credentials.json file and paste in this field <br>\nthat JSON content looks like as below <br>\n<div class=\'\' style=\'background: #d0dfd6;margin-left: 40px;margin-right: 150px;\'>\n\t<p style=\'padding: 20px 0px 20px 00px;color:blueviolet\'>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  { <br>\t\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "type" &nbsp;:&nbsp; "<-------type-------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "project_id" &nbsp;:&nbsp; "<-----------project_id---------------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "private_key_id" &nbsp;:&nbsp; "<---------private_key_id--------------------->"<br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "private_key" &nbsp;:&nbsp; "<-------private_key-------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "client_email" &nbsp;:&nbsp; "<-----------client_email---------------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "client_id" &nbsp;:&nbsp; "<---------client_id--------------------->"<br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "auth_uri" &nbsp;:&nbsp; "<-------auth_uri-------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "token_uri" &nbsp;:&nbsp; "<-----------token_uri---------------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "auth_provider_x509_cert_url" &nbsp;:&nbsp; "<---------auth_provider_x509_cert_url--------------------->"<br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "client_x509_cert_url" &nbsp;:&nbsp; "<---------client_x509_cert_url--------------------->"<br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } <br>\n\t</p>\n</div>\nor <br>\nIf the storage type is AWS then enter your credentials in the below mentioned format <br>\n<div class=\'\' style=\'background: #d0dfd6;margin-left: 40px;margin-right: 150px;\'>\n\t<p style=\'padding: 20px 0px 20px 00px;color:blueviolet\'>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  { <br>\t\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "AWS_ACCESS_KEY_ID" &nbsp;:&nbsp; "<-------access key id-------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "AWS_SECRET_ACCESS_KEY" &nbsp;:&nbsp; "<-----------secret key---------------------->", <br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      "AWS_STORAGE_BUCKET_NAME" &nbsp;:&nbsp; "<---------bucket name--------------------->"<br>\n\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } <br>\n\t</p>\n</div>\n', max_length=3000),
        ),
        migrations.AlterUniqueTogether(
            name='bucketcredentials',
            unique_together={('storage_type', 'storage_bucket_name')},
        ),
    ]
