# Generated by Django 2.2 on 2022-12-20 11:02

import callcenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0145_auto_20221214_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='diallereventlog',
            name='storage_bucket_name',
            field=models.CharField(blank=True, default=callcenter.models.get_bucket_name, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diallereventlog',
            name='recording_file',
            field=models.FileField(blank=True, max_length=1000, storage=callcenter.models.GCPCustomBucketSelection(), upload_to=callcenter.models.get_upload_path),
        ),
    ]
