# Generated by Django 2.2 on 2019-09-10 11:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('alt_numeric', models.CharField(default='', max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('churncount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('FollowUp', 'FollowUp'), ('Snoozed', 'Snoozed'), ('Missedcall', 'Missedcall'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(default='')),
                ('contact_file', models.FileField(blank=True, help_text='Csv fields: number, alt number, state, first name,last name, email, description', upload_to='upload')),
                ('campaign', models.CharField(db_index=True, max_length=100)),
                ('priority', models.IntegerField(default='0')),
                ('caller_id', models.BigIntegerField(default='0')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('order_by', models.CharField(choices=[('Desc', 'Descending'), ('Asc', 'Ascending'), ('Random', 'Random')], default='Desc', max_length=10)),
                ('duplicate_check', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Lead List',
                'verbose_name_plural': 'Lead List',
                'ordering': ['-modified_date'],
                'unique_together': {('name', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TrashContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('alt_numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('FollowUp', 'FollowUp'), ('Snoozed', 'Snoozed'), ('Missedcall', 'Missedcall'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15)),
                ('customer_raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='TempContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('alt_numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('FollowUp', 'FollowUp'), ('Snoozed', 'Snoozed'), ('Missedcall', 'Missedcall'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15)),
                ('customer_raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('phonebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tempcontacts', to='crm.Phonebook')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='SnoozedFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('snoozed_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('alt_numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('FollowUp', 'FollowUp'), ('Snoozed', 'Snoozed'), ('Missedcall', 'Missedcall'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15)),
                ('dialcount', models.IntegerField(default=1)),
                ('schedule_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(default='', max_length=500, null=True)),
                ('customer_raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('phonebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folloupcontacts', to='crm.Phonebook')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('numeric', models.CharField(db_index=True, default='', max_length=50, null=True)),
                ('status', models.CharField(choices=[('NotDialed', 'NotDialed'), ('Queued', 'Queued'), ('Dialed', 'Dialed'), ('Auto-Dialed', 'Auto-Dialed'), ('Locked', 'Locked'), ('NDNC', 'NDNC'), ('Callback', 'Callback'), ('FollowUp', 'FollowUp'), ('Snoozed', 'Snoozed'), ('Missedcall', 'Missedcall'), ('INVALID_NUMBER', 'INVALID_NUMBER'), ('Agent-Answered', 'Agent-Answered'), ('Drop', 'Drop')], db_index=True, default='NotDialed', max_length=15)),
                ('schedule_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(default='', max_length=500, null=True)),
                ('phonebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currnefollowups', to='crm.Phonebook')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='CrmField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('crm_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.ManyToManyField(blank=True, null=True, related_name='campaign_info', to='crm.CampaignInfo')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': '-id',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.Contact')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='phonebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.Phonebook', verbose_name='Lead List'),
        ),
        migrations.AddField(
            model_name='contact',
            name='site',
            field=models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
    ]
