# Generated by Django 2.2 on 2019-11-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20191016_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcontactinfo',
            name='customer_raw_data',
        ),
        migrations.RemoveField(
            model_name='tempcontactinfo',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='tempcontactinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tempcontactinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tempcontactinfo',
            name='status',
        ),
    ]
