# Generated by Django 2.2 on 2020-01-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20200108_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcontactinfo',
            name='contact',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contact'),
        ),
    ]
