# Generated by Django 2.2 on 2020-01-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20191219_1926'),
        ('crm', '0012_tempcontactinfo_contact'),
    ]

    operations = [
    ]
