# Generated by Django 2.2 on 2020-02-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20200123_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tempcontactinfo',
            name='priority',
            field=models.IntegerField(default='0'),
        ),
    ]
