# Generated by Django 2.2 on 2020-02-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('crm', '0015_auto_20200217_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadListPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=30, unique=True)),
                ('priority', models.IntegerField(default='0')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
    ]
