# Generated by Django 2.2 on 2020-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20200218_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
