# Generated by Django 2.2 on 2020-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20200218_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
