# Generated by Django 2.2 on 2020-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_contact_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcontactinfo',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
