# Generated by Django 2.2 on 2020-02-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_tempcontactinfo_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
