# Generated by Django 2.2 on 2020-02-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20200219_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadlistpriority',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
