# Generated by Django 2.2 on 2020-02-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_crmfield_unique_fields'),
        ('crm', '0023_auto_20200220_1924'),
    ]

    operations = [
    ]
