# Generated by Django 2.2 on 2020-02-25 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_merge_20200225_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfield',
            name='unique_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
