# Generated by Django 2.2 on 2020-02-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_downloadreports'),
        ('crm', '0025_auto_20200225_1925'),
    ]

    operations = [
    ]
