# Generated by Django 2.2 on 2020-06-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_phonebook_transfer_contact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='last_updated_contact_count',
            field=models.IntegerField(default=0),
        ),
    ]
