# Generated by Django 2.2 on 2020-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_phonebook_last_updated_contact_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dial_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_connected_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_dialed_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
