# Generated by Django 2.2 on 2020-08-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('crm', '0033_auto_20200709_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_to', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contact')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
    ]
