# Generated by Django 2.2 on 2020-08-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_leadbucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbucket',
            name='reverify_lead',
            field=models.BooleanField(default=False),
        ),
    ]
