# Generated by Django 2.2 on 2020-09-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_crmfield_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlistpriority',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=10),
        ),
    ]
