# Generated by Django 2.2 on 2020-09-15 14:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('crm', '0039_auto_20200903_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBookUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook_file', models.FileField(blank=True, upload_to='upload')),
                ('duplicate_check', models.CharField(blank=True, max_length=100, null=True)),
                ('action_type', models.CharField(blank=True, max_length=100, null=True)),
                ('search_type', models.CharField(blank=True, max_length=100, null=True)),
                ('column_names', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_start', models.BooleanField(default=False)),
                ('phone_inst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phonebook_upload', to='crm.Phonebook')),
                ('site', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site')),
            ],
        ),
    ]
