# Generated by Django 2.2 on 2020-09-18 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_phonebookupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
