# Generated by Django 2.2 on 2020-09-17 17:26

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_phonebookupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadreports',
            name='downloaded_file',
            field=models.FileField(blank=True, help_text='Click to downlad file', upload_to=crm.models.get_upload_path),
        ),
    ]
