# Generated by Django 2.2 on 2020-09-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_contact_customer_raw_data'),
        ('crm', '0041_auto_20200917_1726'),
    ]

    operations = [
    ]
