# Generated by Django 2.2 on 2020-11-02 18:32

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_merge_20200921_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric', models.CharField(default='', max_length=50, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=30, null=True)),
                ('alt_numeric', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
