# Generated by Django 2.2 on 2021-03-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_alternatecontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternatecontact',
            options={'ordering': ['id']},
        ),
    ]
