# Generated by Django 2.2 on 2022-06-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_auto_20210322_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], db_index=True, default='Active', max_length=10),
        ),
    ]
