# Generated by Django 2.2 on 2022-06-06 11:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_auto_20220530_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric', models.CharField(max_length=20)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('customer_raw_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleMasterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'scheduled'), ('started', 'started'), ('dbsaving', 'dbsaving'), ('finished', 'finished')], default='scheduled', max_length=40, null=True)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('mcdata', models.FileField(blank=True, upload_to='upload')),
                ('proper_mcdata', models.FileField(blank=True, upload_to='upload')),
                ('improper_mcdata', models.FileField(blank=True, upload_to='upload')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
