# Generated by Django 2.2 on 2022-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_auto_20220616_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
