# Generated by Django 2.2 on 2022-07-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_mastercontact_schedulemastercontact'),
        ('crm', '0046_auto_20220622_1731'),
    ]

    operations = [
    ]
