# Generated by Django 2.2 on 2022-07-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_merge_20220714_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebookupload',
            name='phonebook_file',
            field=models.FileField(blank=True, upload_to='upload'),
        ),
    ]
