# Generated by Django 2.2 on 2022-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_auto_20220720_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='priority',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
