# Generated by Django 2.2 on 2022-08-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_auto_20220809_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='priority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
