# Generated by Django 2.2 on 2022-08-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_auto_20220822_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='campaign',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempcontactinfo',
            name='priority',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
