
---
name: Docker Image CI

on:
  push:
    branches: [ '*' ]
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Environment
      id: preenv
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        IMAGE_ID=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        [ "$VERSION" == "main" ] && VERSION=latest
        echo  "::set-output name=IMAGE_ID::$IMAGE_ID"
        echo  "::set-output name=VERSION::$VERSION"

    - name: Build Flexydial-app Docker Image
      run: |
        docker build . \
          --build-arg COMMIT_SHA="${{ github.sha }}" \
          --build-arg FLEXYDIAL_VERSION="6.0.1" \
          --build-arg FLEXYDIAL_BRANCH="${{ github.ref }}" \
          --build-arg FLEXYDIAL_IMAGE_DATE_CREATED="${{ steps.preenv.outputs.date }}" \
          --build-arg FLEXYDIAL_IMAGE_REPOSITORY=${{ github.repository }} \
          --tag ${{ steps.preenv.outputs.IMAGE_ID }}:${{ steps.preenv.outputs.VERSION }} --label "runnumber=${{github.run_number}}"

    - name: Build Flexydial-static Docker Image
      run: |
        cd static
        docker build . \
          --build-arg COMMIT_SHA="${{ github.sha }}" \
          --build-arg FLEXYDIAL_VERSION="6.0.1" \
          --build-arg FLEXYDIAL_BRANCH="${{ github.ref }}" \
          --build-arg FLEXYDIAL_IMAGE_DATE_CREATED="${{ steps.preenv.outputs.date }}" \
          --build-arg FLEXYDIAL_IMAGE_REPOSITORY=${{ github.repository }} \
          --tag ${{ steps.preenv.outputs.IMAGE_ID }}-static:${{ steps.preenv.outputs.VERSION }} --label "runnumber=${{github.run_number}}"
        cd ../

    - name: Build Flexydial-websocket Docker Image
      run: |
        cd fs-dialplan
        docker build . \
          --build-arg COMMIT_SHA="${{ github.sha }}" \
          --build-arg FLEXYDIAL_VERSION="6.0.1" \
          --build-arg FLEXYDIAL_BRANCH="${{ github.ref }}" \
          --build-arg FLEXYDIAL_IMAGE_DATE_CREATED="${{ steps.preenv.outputs.date }}" \
          --build-arg FLEXYDIAL_IMAGE_REPOSITORY=${{ github.repository }} \
          --tag ${{ steps.preenv.outputs.IMAGE_ID }}-websocket:${{ steps.preenv.outputs.VERSION }} --label "runnumber=${{github.run_number}}"
        cd ../

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true

    - name: Push image to Github Registry
      run: |
        docker push ${{ steps.preenv.outputs.IMAGE_ID }}:${{ steps.preenv.outputs.VERSION }}
        docker push ${{ steps.preenv.outputs.IMAGE_ID }}-static:${{ steps.preenv.outputs.VERSION }}
        docker push ${{ steps.preenv.outputs.IMAGE_ID }}-websocket:${{ steps.preenv.outputs.VERSION }}
